export type Nationality = {
  code: string;
  name: string; // Demonym (e.g. "Nigerian", "Canadian", "British")
  country: string; // Country name
  flag: string;
};

export const nationalities: Nationality[] = [
  { code: "AF", name: "Afghan", country: "Afghanistan", flag: "🇦🇫" },
  { code: "AL", name: "Albanian", country: "Albania", flag: "🇦🇱" },
  { code: "DZ", name: "Algerian", country: "Algeria", flag: "🇩🇿" },
  { code: "US", name: "American", country: "United States", flag: "🇺🇸" },
  { code: "AD", name: "Andorran", country: "Andorra", flag: "🇦🇩" },
  { code: "AO", name: "Angolan", country: "Angola", flag: "🇦🇴" },
  { code: "AG", name: "Antiguan / Barbudan", country: "Antigua & Barbuda", flag: "🇦🇬" },
  { code: "AR", name: "Argentine", country: "Argentina", flag: "🇦🇷" },
  { code: "AM", name: "Armenian", country: "Armenia", flag: "🇦🇲" },
  { code: "AU", name: "Australian", country: "Australia", flag: "🇦🇺" },
  { code: "AT", name: "Austrian", country: "Austria", flag: "🇦🇹" },
  { code: "AZ", name: "Azerbaijani", country: "Azerbaijan", flag: "🇦🇿" },
  { code: "BS", name: "Bahamian", country: "Bahamas", flag: "🇧🇸" },
  { code: "BH", name: "Bahraini", country: "Bahrain", flag: "🇧🇭" },
  { code: "BD", name: "Bangladeshi", country: "Bangladesh", flag: "🇧🇩" },
  { code: "BB", name: "Barbadian", country: "Barbados", flag: "🇧🇧" },
  { code: "BY", name: "Belarusian", country: "Belarus", flag: "🇧🇾" },
  { code: "BE", name: "Belgian", country: "Belgium", flag: "🇧🇪" },
  { code: "BZ", name: "Belizean", country: "Belize", flag: "🇧🇿" },
  { code: "BJ", name: "Beninese", country: "Benin", flag: "🇧🇯" },
  { code: "BT", name: "Bhutanese", country: "Bhutan", flag: "🇧🇹" },
  { code: "BO", name: "Bolivian", country: "Bolivia", flag: "🇧🇴" },
  { code: "BA", name: "Bosnian / Herzegovinian", country: "Bosnia & Herzegovina", flag: "🇧🇦" },
  { code: "BW", name: "Motswana / Botswana", country: "Botswana", flag: "🇧🇼" },
  { code: "BR", name: "Brazilian", country: "Brazil", flag: "🇧🇷" },
  { code: "GB", name: "British", country: "United Kingdom", flag: "🇬🇧" },
  { code: "BN", name: "Bruneian", country: "Brunei", flag: "🇧🇳" },
  { code: "BG", name: "Bulgarian", country: "Bulgaria", flag: "🇧🇬" },
  { code: "BF", name: "Burkinabé", country: "Burkina Faso", flag: "🇧🇫" },
  { code: "BI", name: "Burundian", country: "Burundi", flag: "🇧🇮" },
  { code: "KH", name: "Cambodian", country: "Cambodia", flag: "🇰🇭" },
  { code: "CM", name: "Cameroonian", country: "Cameroon", flag: "🇨🇲" },
  { code: "CA", name: "Canadian", country: "Canada", flag: "🇨🇦" },
  { code: "CV", name: "Cape Verdean", country: "Cape Verde", flag: "🇨🇻" },
  { code: "CF", name: "Central African", country: "Central African Republic", flag: "🇨🇫" },
  { code: "TD", name: "Chadian", country: "Chad", flag: "🇹🇩" },
  { code: "CL", name: "Chilean", country: "Chile", flag: "🇨🇱" },
  { code: "CN", name: "Chinese", country: "China", flag: "🇨🇳" },
  { code: "CO", name: "Colombian", country: "Colombia", flag: "🇨🇴" },
  { code: "KM", name: "Comorian", country: "Comoros", flag: "🇰🇲" },
  { code: "CG", name: "Congolese", country: "Congo - Brazzaville", flag: "🇨🇬" },
  { code: "CD", name: "Congolese (DRC)", country: "Congo - Kinshasa", flag: "🇨🇩" },
  { code: "CR", name: "Costa Rican", country: "Costa Rica", flag: "🇨🇷" },
  { code: "CI", name: "Ivorian", country: "Côte d’Ivoire", flag: "🇨🇮" },
  { code: "HR", name: "Croatian", country: "Croatia", flag: "🇭🇷" },
  { code: "CU", name: "Cuban", country: "Cuba", flag: "🇨🇺" },
  { code: "CY", name: "Cypriot", country: "Cyprus", flag: "🇨🇾" },
  { code: "CZ", name: "Czech", country: "Czechia", flag: "🇨🇿" },
  { code: "DK", name: "Danish", country: "Denmark", flag: "🇩🇰" },
  { code: "DJ", name: "Djiboutian", country: "Djibouti", flag: "🇩🇯" },
  { code: "DM", name: "Dominican (Dominica)", country: "Dominica", flag: "🇩🇲" },
  { code: "DO", name: "Dominican (Dominican Rep.)", country: "Dominican Republic", flag: "🇩🇴" },
  { code: "NL", name: "Dutch", country: "Netherlands", flag: "🇳🇱" },
  { code: "EC", name: "Ecuadorean", country: "Ecuador", flag: "🇪🇨" },
  { code: "EG", name: "Egyptian", country: "Egypt", flag: "🇪🇬" },
  { code: "SV", name: "Salvadoran", country: "El Salvador", flag: "🇸🇻" },
  { code: "AE", name: "Emirati", country: "United Arab Emirates", flag: "🇦🇪" },
  { code: "GQ", name: "Equatorial Guinean", country: "Equatorial Guinea", flag: "🇬🇶" },
  { code: "ER", name: "Eritrean", country: "Eritrea", flag: "🇪🇷" },
  { code: "EE", name: "Estonian", country: "Estonia", flag: "🇪🇪" },
  { code: "SZ", name: "Swazi", country: "Eswatini", flag: "🇸🇿" },
  { code: "ET", name: "Ethiopian", country: "Ethiopia", flag: "🇪🇹" },
  { code: "FJ", name: "Fijian", country: "Fiji", flag: "🇫🇯" },
  { code: "PH", name: "Filipino", country: "Philippines", flag: "🇵🇭" },
  { code: "FI", name: "Finnish", country: "Finland", flag: "🇫🇮" },
  { code: "FR", name: "French", country: "France", flag: "🇫🇷" },
  { code: "GA", name: "Gabonese", country: "Gabon", flag: "🇬🇦" },
  { code: "GM", name: "Gambian", country: "Gambia", flag: "🇬🇲" },
  { code: "GE", name: "Georgian", country: "Georgia", flag: "🇬🇪" },
  { code: "DE", name: "German", country: "Germany", flag: "🇩🇪" },
  { code: "GH", name: "Ghanaian", country: "Ghana", flag: "🇬🇭" },
  { code: "GR", name: "Greek", country: "Greece", flag: "🇬🇷" },
  { code: "GD", name: "Grenadian", country: "Grenada", flag: "🇬🇩" },
  { code: "GT", name: "Guatemalan", country: "Guatemala", flag: "🇬🇹" },
  { code: "GN", name: "Guinean", country: "Guinea", flag: "🇬🇳" },
  { code: "GW", name: "Bissau-Guinean", country: "Guinea-Bissau", flag: "🇬🇼" },
  { code: "GY", name: "Guyanese", country: "Guyana", flag: "🇬🇾" },
  { code: "HT", name: "Haitian", country: "Haiti", flag: "🇭🇹" },
  { code: "HN", name: "Honduran", country: "Honduras", flag: "🇭🇳" },
  { code: "HU", name: "Hungarian", country: "Hungary", flag: "🇭🇺" },
  { code: "IS", name: "Icelandic", country: "Iceland", flag: "🇮🇸" },
  { code: "IN", name: "Indian", country: "India", flag: "🇮🇳" },
  { code: "ID", name: "Indonesian", country: "Indonesia", flag: "🇮🇩" },
  { code: "IR", name: "Iranian", country: "Iran", flag: "🇮🇷" },
  { code: "IQ", name: "Iraqi", country: "Iraq", flag: "🇮🇶" },
  { code: "IE", name: "Irish", country: "Ireland", flag: "🇮🇪" },
  { code: "IL", name: "Israeli", country: "Israel", flag: "🇮🇱" },
  { code: "IT", name: "Italian", country: "Italy", flag: "🇮🇹" },
  { code: "JM", name: "Jamaican", country: "Jamaica", flag: "🇯🇲" },
  { code: "JP", name: "Japanese", country: "Japan", flag: "🇯🇵" },
  { code: "JO", name: "Jordanian", country: "Jordan", flag: "🇯🇴" },
  { code: "KZ", name: "Kazakhstani", country: "Kazakhstan", flag: "🇰🇿" },
  { code: "KE", name: "Kenyan", country: "Kenya", flag: "🇰🇪" },
  { code: "KI", name: "I-Kiribati", country: "Kiribati", flag: "🇰🇮" },
  { code: "KW", name: "Kuwaiti", country: "Kuwait", flag: "🇰🇼" },
  { code: "KG", name: "Kyrgyzstani", country: "Kyrgyzstan", flag: "🇰🇬" },
  { code: "LA", name: "Lao", country: "Laos", flag: "🇱🇦" },
  { code: "LV", name: "Latvian", country: "Latvia", flag: "🇱🇻" },
  { code: "LB", name: "Lebanese", country: "Lebanon", flag: "🇱🇧" },
  { code: "LS", name: "Basotho", country: "Lesotho", flag: "🇱🇸" },
  { code: "LR", name: "Liberian", country: "Liberia", flag: "🇱🇷" },
  { code: "LY", name: "Libyan", country: "Libya", flag: "🇱🇾" },
  { code: "LI", name: "Liechtensteiner", country: "Liechtenstein", flag: "🇱🇮" },
  { code: "LT", name: "Lithuanian", country: "Lithuania", flag: "🇱🇹" },
  { code: "LU", name: "Luxembourger", country: "Luxembourg", flag: "🇱🇺" },
  { code: "MG", name: "Malagasy", country: "Madagascar", flag: "🇲🇬" },
  { code: "MW", name: "Malawian", country: "Malawi", flag: "🇲🇼" },
  { code: "MY", name: "Malaysian", country: "Malaysia", flag: "🇲🇾" },
  { code: "MV", name: "Maldivian", country: "Maldives", flag: "🇲🇻" },
  { code: "ML", name: "Malian", country: "Mali", flag: "🇲🇱" },
  { code: "MT", name: "Maltese", country: "Malta", flag: "🇲🇹" },
  { code: "MH", name: "Marshallese", country: "Marshall Islands", flag: "🇲🇭" },
  { code: "MR", name: "Mauritanian", country: "Mauritania", flag: "🇲🇷" },
  { code: "MU", name: "Mauritian", country: "Mauritius", flag: "🇲🇺" },
  { code: "MX", name: "Mexican", country: "Mexico", flag: "🇲🇽" },
  { code: "FM", name: "Micronesian", country: "Micronesia", flag: "🇫🇲" },
  { code: "MD", name: "Moldovan", country: "Moldova", flag: "🇲🇩" },
  { code: "MC", name: "Monegasc", country: "Monaco", flag: "🇲🇨" },
  { code: "MN", name: "Mongolian", country: "Mongolia", flag: "🇲🇳" },
  { code: "ME", name: "Montenegrin", country: "Montenegro", flag: "🇲🇪" },
  { code: "MA", name: "Moroccan", country: "Morocco", flag: "🇲🇦" },
  { code: "MZ", name: "Mozambican", country: "Mozambique", flag: "🇲🇿" },
  { code: "MM", name: "Burmese", country: "Myanmar (Burma)", flag: "🇲🇲" },
  { code: "NA", name: "Namibian", country: "Namibia", flag: "🇳🇦" },
  { code: "NR", name: "Nauruan", country: "Nauru", flag: "🇳🇷" },
  { code: "NP", name: "Nepali", country: "Nepal", flag: "🇳🇵" },
  { code: "NZ", name: "New Zealander", country: "New Zealand", flag: "🇳🇿" },
  { code: "NI", name: "Nicaraguan", country: "Nicaragua", flag: "🇳🇮" },
  { code: "NE", name: "Nigerien", country: "Niger", flag: "🇳🇪" },
  { code: "NG", name: "Nigerian", country: "Nigeria", flag: "🇳🇬" },
  { code: "KP", name: "North Korean", country: "North Korea", flag: "🇰🇵" },
  { code: "MK", name: "Macedonian", country: "North Macedonia", flag: "🇲🇰" },
  { code: "NO", name: "Norwegian", country: "Norway", flag: "🇳🇴" },
  { code: "OM", name: "Omani", country: "Oman", flag: "🇴🇲" },
  { code: "PK", name: "Pakistani", country: "Pakistan", flag: "🇵🇰" },
  { code: "PW", name: "Palauan", country: "Palau", flag: "🇵🇼" },
  { code: "PS", name: "Palestinian", country: "Palestinian Territories", flag: "🇵🇸" },
  { code: "PA", name: "Panamanian", country: "Panama", flag: "🇵🇦" },
  { code: "PG", name: "Papua New Guinean", country: "Papua New Guinea", flag: "🇵🇬" },
  { code: "PY", name: "Paraguayan", country: "Paraguay", flag: "🇵🇾" },
  { code: "PE", name: "Peruvian", country: "Peru", flag: "🇵🇪" },
  { code: "PL", name: "Polish", country: "Poland", flag: "🇵🇱" },
  { code: "PT", name: "Portuguese", country: "Portugal", flag: "🇵🇹" },
  { code: "QA", name: "Qatari", country: "Qatar", flag: "🇶🇦" },
  { code: "RO", name: "Romanian", country: "Romania", flag: "🇷🇴" },
  { code: "RU", name: "Russian", country: "Russia", flag: "🇷🇺" },
  { code: "RW", name: "Rwandan", country: "Rwanda", flag: "🇷🇼" },
  { code: "WS", name: "Samoan", country: "Samoa", flag: "🇼🇸" },
  { code: "SM", name: "Sammarinese", country: "San Marino", flag: "🇸🇲" },
  { code: "ST", name: "São Toméan", country: "São Tomé & Príncipe", flag: "🇸🇹" },
  { code: "SA", name: "Saudi", country: "Saudi Arabia", flag: "🇸🇦" },
  { code: "SN", name: "Senegalese", country: "Senegal", flag: "🇸🇳" },
  { code: "RS", name: "Serbian", country: "Serbia", flag: "🇷🇸" },
  { code: "SC", name: "Seychellois", country: "Seychelles", flag: "🇸🇨" },
  { code: "SL", name: "Sierra Leonean", country: "Sierra Leone", flag: "🇸🇱" },
  { code: "SG", name: "Singaporean", country: "Singapore", flag: "🇸🇬" },
  { code: "SK", name: "Slovak", country: "Slovakia", flag: "🇸🇰" },
  { code: "SI", name: "Slovenian", country: "Slovenia", flag: "🇸🇮" },
  { code: "SB", name: "Solomon Islander", country: "Solomon Islands", flag: "🇸🇧" },
  { code: "SO", name: "Somali", country: "Somalia", flag: "🇸🇴" },
  { code: "ZA", name: "South African", country: "South Africa", flag: "🇿🇦" },
  { code: "KR", name: "South Korean", country: "South Korea", flag: "🇰🇷" },
  { code: "SS", name: "South Sudanese", country: "South Sudan", flag: "🇸🇸" },
  { code: "ES", name: "Spanish", country: "Spain", flag: "🇪🇸" },
  { code: "LK", name: "Sri Lankan", country: "Sri Lanka", flag: "🇱🇰" },
  { code: "SD", name: "Sudanese", country: "Sudan", flag: "🇸🇩" },
  { code: "SR", name: "Surinamese", country: "Suriname", flag: "🇸🇷" },
  { code: "SE", name: "Swedish", country: "Sweden", flag: "🇸🇪" },
  { code: "CH", name: "Swiss", country: "Switzerland", flag: "🇨🇭" },
  { code: "SY", name: "Syrian", country: "Syria", flag: "🇸🇾" },
  { code: "TW", name: "Taiwanese", country: "Taiwan", flag: "🇹🇼" },
  { code: "TJ", name: "Tajikstani", country: "Tajikistan", flag: "🇹🇯" },
  { code: "TZ", name: "Tanzanian", country: "Tanzania", flag: "🇹🇿" },
  { code: "TH", name: "Thai", country: "Thailand", flag: "🇹🇭" },
  { code: "TG", name: "Togolese", country: "Togo", flag: "🇹🇬" },
  { code: "TO", name: "Tongan", country: "Tonga", flag: "🇹🇴" },
  { code: "TT", name: "Trinidadian / Tobagonian", country: "Trinidad & Tobago", flag: "🇹🇹" },
  { code: "TN", name: "Tunisian", country: "Tunisia", flag: "🇹🇳" },
  { code: "TR", name: "Turkish", country: "Turkey", flag: "🇹🇷" },
  { code: "TM", name: "Turkmen", country: "Turkmenistan", flag: "🇹🇲" },
  { code: "TV", name: "Tuvaluan", country: "Tuvalu", flag: "🇹🇻" },
  { code: "UG", name: "Ugandan", country: "Uganda", flag: "🇺🇬" },
  { code: "UA", name: "Ukrainian", country: "Ukraine", flag: "🇺🇦" },
  { code: "UY", name: "Uruguayan", country: "Uruguay", flag: "🇺🇾" },
  { code: "UZ", name: "Uzbekistani", country: "Uzbekistan", flag: "🇺🇿" },
  { code: "VU", name: "Ni-Vanuatu", country: "Vanuatu", flag: "🇻🇺" },
  { code: "VE", name: "Venezuelan", country: "Venezuela", flag: "🇻🇪" },
  { code: "VN", name: "Vietnamese", country: "Vietnam", flag: "🇻🇳" },
  { code: "YE", name: "Yemeni", country: "Yemen", flag: "🇾🇪" },
  { code: "ZM", name: "Zambian", country: "Zambia", flag: "🇿🇲" },
  { code: "ZW", name: "Zimbabwean", country: "Zimbabwe", flag: "🇿🇼" },
];

export function findNationality(value: string | null | undefined): Nationality | undefined {
  if (!value) return undefined;
  const lower = value.trim().toLowerCase();
  return nationalities.find(
    (n) =>
      n.name.toLowerCase() === lower ||
      n.country.toLowerCase() === lower ||
      n.code.toLowerCase() === lower
  );
}
