import {
  Injectable,
  UnauthorizedException,
  Logger,
} from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { RunSeedDto } from './dto/run-seed.dto';
import {
  UserRole,
  AgencyVerificationStatus,
  AgencyListingStatus,
  AgencyUserRole,
  AgencyStaffStatus,
  AgencyDocumentKind,
  AgencyDocumentStatus,
  AssignmentStatus,
  VisaDocumentStatus,
  PassportCategory,
  PassportValidity,
  BookletType,
  PassportApplicationStatus,
  Gender,
  Prisma,
} from '@prisma/client';
import { createHash } from 'crypto';

@Injectable()
export class SeedService {
  private readonly logger = new Logger(SeedService.name);
  private readonly DEFAULT_SECRET_CODE = 'WORLD_PORTAL_SEED_2026_SECURE';
  private readonly DEFAULT_PASSWORD = 'Password@2';

  constructor(private readonly prisma: PrismaService) {}

  private hashPassword(password: string): string {
    return createHash('sha256').update(password).digest('hex');
  }

  /**
   * Remote database seeding triggered via REST API with secret code authorization
   */
  async runSeed(dto: RunSeedDto) {
    const requiredCode = process.env.SEED_SECRET_CODE || this.DEFAULT_SECRET_CODE;

    if (dto.secretCode !== requiredCode) {
      this.logger.warn(`Unauthorized seeding attempt with code=${dto.secretCode}`);
      throw new UnauthorizedException('Invalid seeding secret code');
    }

    this.logger.log('Seeding database with 10+ Agencies and 10+ Professionals...');
    const defaultPasswordHash = this.hashPassword(this.DEFAULT_PASSWORD);

    // 1. Manager Profile
    const manager = await this.prisma.profile.upsert({
      where: { email: 'manager@loveworld.com' },
      update: {},
      create: {
        email: 'manager@loveworld.com',
        firstName: 'System',
        lastName: 'Manager',
        role: UserRole.MANAGER,
        externalAuthId: 'external-auth-manager-001',
        isActive: true,
      },
    });

    // 2. Bank Accounts
    await this.prisma.bankAccount.upsert({
      where: { id: 'bank-usd-001' },
      update: {},
      create: {
        id: 'bank-usd-001',
        bankName: 'Zenith Bank',
        accountName: 'World Portal Global Ltd',
        accountNumber: '5070192834',
        swiftCode: 'ZEIBNGLA',
        currency: 'USD',
        instructions: 'Please include transaction reference in payment remarks.',
        isActive: true,
      },
    });

    await this.prisma.bankAccount.upsert({
      where: { id: 'bank-ngn-001' },
      update: {},
      create: {
        id: 'bank-ngn-001',
        bankName: 'GTBank',
        accountName: 'World Portal Services Nigeria',
        accountNumber: '0129485763',
        currency: 'NGN',
        instructions: 'Transfer to GTBank NGN Account.',
        isActive: true,
      },
    });

    // 3. Agencies Dataset (10 Agencies)
    const agenciesData = [
      {
        slug: 'apex-security-services',
        name: 'Apex Security Services',
        legalName: 'Apex Security Nigeria Limited',
        registrationNumber: 'RC-1048291',
        countryCode: 'NG',
        country: 'Nigeria',
        cities: ['Lagos', 'Abuja'],
        categories: ['security'],
        summary: 'Premium close-protection and event security agency.',
        about: 'Apex Security provides vetted close protection bodyguards and event security.',
        email: 'owner@apexsecurity.ng',
        phone: '+2348012345678',
        website: 'https://apexsecurity.ng',
        yearFounded: 2018,
        staffCount: 45,
        languages: ['English', 'Yoruba'],
        verification: AgencyVerificationStatus.VERIFIED,
        listingStatus: AgencyListingStatus.LIVE,
        rating: 4.9,
      },
      {
        slug: 'vanguard-executive-transit',
        name: 'Vanguard Executive Transit',
        legalName: 'Vanguard Mobility Services Ltd',
        registrationNumber: 'RC-993821',
        countryCode: 'NG',
        country: 'Nigeria',
        cities: ['Abuja'],
        categories: ['driving'],
        summary: 'Armored SUVs and executive chauffeur services.',
        about: 'Chauffeured transportation for corporate executives and diplomats.',
        email: 'manager@vanguardtransit.ng',
        phone: '+2348098765432',
        yearFounded: 2020,
        staffCount: 18,
        languages: ['English', 'Hausa'],
        verification: AgencyVerificationStatus.PENDING,
        listingStatus: AgencyListingStatus.IN_REVIEW,
        rating: 4.7,
      },
      {
        slug: 'lagos-culinary-chefs',
        name: 'Lagos Culinary & Event Chefs',
        legalName: 'Lagos Culinary Group Ltd',
        registrationNumber: 'RC-881234',
        countryCode: 'NG',
        country: 'Nigeria',
        cities: ['Lagos'],
        categories: ['catering'],
        summary: 'Gourmet dining and private chef services for VIPs.',
        about: 'Bespoke culinary experiences delivered at private residences and yachts.',
        email: 'info@lagoschefs.ng',
        phone: '+2348033334444',
        yearFounded: 2019,
        staffCount: 12,
        languages: ['English'],
        verification: AgencyVerificationStatus.UNVERIFIED,
        listingStatus: AgencyListingStatus.DRAFT,
        rating: 4.6,
      },
      {
        slug: 'horizon-escort-logistics',
        name: 'Horizon Escort & Logistics',
        legalName: 'Horizon Global Logistics Ltd',
        registrationNumber: 'RC-772819',
        countryCode: 'NG',
        country: 'Nigeria',
        cities: ['Lagos', 'Port Harcourt'],
        categories: ['logistics'],
        summary: 'Airport fast-track, protocol, and baggage customs clearance.',
        about: 'Full protocol fast-track escort at major international airports.',
        email: 'ops@horizonlogistics.ng',
        phone: '+2348055556666',
        yearFounded: 2017,
        staffCount: 30,
        languages: ['English', 'French'],
        verification: AgencyVerificationStatus.VERIFIED,
        listingStatus: AgencyListingStatus.LIVE,
        rating: 4.8,
      },
      {
        slug: 'tokyo-diplomatic-interpreters',
        name: 'Tokyo Diplomatic Interpreters',
        legalName: 'Tokyo Interpretation Co Ltd',
        registrationNumber: 'TK-44821',
        countryCode: 'JP',
        country: 'Japan',
        cities: ['Tokyo', 'Osaka'],
        categories: ['interpreting'],
        summary: 'Certified Japanese-English business and diplomatic interpreters.',
        about: 'Simultaneous and consecutive interpretation for global conferences.',
        email: 'contact@tokyointerpreters.jp',
        phone: '+81312345678',
        yearFounded: 2015,
        staffCount: 22,
        languages: ['English', 'Japanese'],
        verification: AgencyVerificationStatus.VERIFIED,
        listingStatus: AgencyListingStatus.LIVE,
        rating: 5.0,
      },
      {
        slug: 'santorini-sunset-events',
        name: 'Santorini Sunset Events',
        legalName: 'Santorini Event Planners SA',
        registrationNumber: 'EL-99182',
        countryCode: 'GR',
        country: 'Greece',
        cities: ['Santorini', 'Athens'],
        categories: ['events'],
        summary: 'Luxury destination wedding and private event production.',
        about: 'Full-service event coordination overlooking the Caldera.',
        email: 'hello@santorinievents.gr',
        phone: '+302286012345',
        yearFounded: 2016,
        staffCount: 15,
        languages: ['English', 'Greek'],
        verification: AgencyVerificationStatus.VERIFIED,
        listingStatus: AgencyListingStatus.LIVE,
        rating: 4.9,
      },
      {
        slug: 'sahara-adventure-guides',
        name: 'Sahara Adventure Guides',
        legalName: 'Sahara Expeditions SARL',
        registrationNumber: 'MA-33912',
        countryCode: 'MA',
        country: 'Morocco',
        cities: ['Marrakech', 'Casablanca'],
        categories: ['tour_guide'],
        summary: 'Licensed desert expeditions and cultural Medina walking tours.',
        about: 'Private guided tours through ancient souks and Atlas Mountain treks.',
        email: 'tours@saharaguides.ma',
        phone: '+212524112233',
        yearFounded: 2014,
        staffCount: 25,
        languages: ['English', 'Arabic', 'French'],
        verification: AgencyVerificationStatus.VERIFIED,
        listingStatus: AgencyListingStatus.LIVE,
        rating: 4.8,
      },
      {
        slug: 'capetown-childcare-specialists',
        name: 'Cape Town Childcare Specialists',
        legalName: 'Cape Nanny Network Pty Ltd',
        registrationNumber: 'ZA-55910',
        countryCode: 'ZA',
        country: 'South Africa',
        cities: ['Cape Town'],
        categories: ['childcare'],
        summary: 'Background-checked nannies and hotel babysitters for travelers.',
        about: 'First-aid certified, vetted childcare professionals for visiting families.',
        email: 'care@capetownnannies.co.za',
        phone: '+27214001122',
        yearFounded: 2018,
        staffCount: 40,
        languages: ['English', 'Afrikaans'],
        verification: AgencyVerificationStatus.VERIFIED,
        listingStatus: AgencyListingStatus.LIVE,
        rating: 4.9,
      },
      {
        slug: 'riviera-medical-escorts',
        name: 'Riviera Medical & Wellness Escorts',
        legalName: 'Riviera Care Services SAS',
        registrationNumber: 'FR-88219',
        countryCode: 'FR',
        country: 'France',
        cities: ['Nice', 'Cannes'],
        categories: ['medical'],
        summary: 'Registered nurses and medical companions for international travelers.',
        about: '24/7 medical escort and private nursing care on the French Riviera.',
        email: 'contact@rivieramedical.fr',
        phone: '+33493123456',
        yearFounded: 2019,
        staffCount: 14,
        languages: ['English', 'French'],
        verification: AgencyVerificationStatus.VERIFIED,
        listingStatus: AgencyListingStatus.LIVE,
        rating: 5.0,
      },
      {
        slug: 'highland-pure-cleaning',
        name: 'Highland Pure Cleaning & Sanitation',
        legalName: 'Highland Cleaning Services Ltd',
        registrationNumber: 'SC-11029',
        countryCode: 'GB',
        country: 'United Kingdom',
        cities: ['Edinburgh', 'Glasgow'],
        categories: ['cleaning'],
        summary: 'Deep cleaning and sanitation for vacation rentals and estates.',
        about: 'Eco-friendly estate turnover and luxury property cleaning.',
        email: 'info@highlandcleaning.co.uk',
        phone: '+441314960000',
        yearFounded: 2016,
        staffCount: 20,
        languages: ['English'],
        verification: AgencyVerificationStatus.VERIFIED,
        listingStatus: AgencyListingStatus.LIVE,
        rating: 4.7,
      },
    ];

    for (const a of agenciesData) {
      const agency = await this.prisma.agency.upsert({
        where: { slug: a.slug },
        update: { verification: a.verification, listingStatus: a.listingStatus },
        create: {
          slug: a.slug,
          name: a.name,
          legalName: a.legalName,
          registrationNumber: a.registrationNumber,
          countryCode: a.countryCode,
          country: a.country,
          cities: a.cities,
          categories: a.categories,
          summary: a.summary,
          about: a.about,
          email: a.email,
          phone: a.phone,
          yearFounded: a.yearFounded,
          staffCount: a.staffCount,
          languages: a.languages,
          verification: a.verification,
          listingStatus: a.listingStatus,
          rating: new Prisma.Decimal(a.rating),
          completedJobs: Math.floor(Math.random() * 50) + 10,
        },
      });

      // Agency User Account
      await this.prisma.agencyUser.upsert({
        where: { email: a.email },
        update: { passwordHash: defaultPasswordHash },
        create: {
          name: `${a.name} Manager`,
          email: a.email,
          passwordHash: defaultPasswordHash,
          role: AgencyUserRole.OWNER,
          agencyId: agency.id,
        },
      });
    }

    // 4. Professionals Dataset (10 Professionals)
    const professionalsData = [
      {
        slug: 'elena-marousi',
        name: 'Elena Marousi',
        title: 'Caldera & Golden-Hour Portrait Photographer',
        category: 'photographer',
        bio: 'Shoots the caldera almost every evening. Relaxed direction and natural lighting.',
        countryCode: 'GR',
        country: 'Greece',
        city: 'Santorini',
        hourlyRate: 140.0,
        rating: 4.9,
        jobs: 240,
        languages: ['English', 'Greek'],
      },
      {
        slug: 'kenji-watanabe',
        name: 'Kenji Watanabe',
        title: 'Neon Street & Documentary Photographer',
        category: 'photographer',
        bio: 'Former magazine photojournalist capturing Shinjuku and Shibuya night walks.',
        countryCode: 'JP',
        country: 'Japan',
        city: 'Tokyo',
        hourlyRate: 120.0,
        rating: 4.8,
        jobs: 310,
        languages: ['Japanese', 'English'],
      },
      {
        slug: 'putu-ardana',
        name: 'Putu Ardana',
        title: 'Cinematic Travel Film-Maker & Drone Pilot',
        category: 'videographer',
        bio: 'Short travel films with a drone and gimbal, delivered within 48 hours.',
        countryCode: 'ID',
        country: 'Indonesia',
        city: 'Bali',
        hourlyRate: 97.5,
        rating: 4.9,
        jobs: 180,
        languages: ['Indonesian', 'English'],
      },
      {
        slug: 'marina-castro',
        name: 'Marina Castro',
        title: 'Event & Lifestyle Videographer',
        category: 'videographer',
        bio: 'Covers launch events, birthdays, and travel experiences across Rio.',
        countryCode: 'BR',
        country: 'Brazil',
        city: 'Rio de Janeiro',
        hourlyRate: 85.0,
        rating: 4.8,
        jobs: 145,
        languages: ['Portuguese', 'English', 'Spanish'],
      },
      {
        slug: 'hicham-benali',
        name: 'Hicham Benali',
        title: 'Private Chef & Moroccan Culinary Master',
        category: 'chef',
        bio: 'Traditional tagines and modern Mediterranean dining at private villas.',
        countryCode: 'MA',
        country: 'Morocco',
        city: 'Marrakech',
        hourlyRate: 105.0,
        rating: 5.0,
        jobs: 98,
        languages: ['Arabic', 'French', 'English'],
      },
      {
        slug: 'aya-kobayashi',
        name: 'Aya Kobayashi',
        title: 'Senior Private Guide & Translator',
        category: 'interpreting',
        bio: 'Licensed bilingual tour guide and interpreter with 10 years experience.',
        countryCode: 'JP',
        country: 'Japan',
        city: 'Tokyo',
        hourlyRate: 65.0,
        rating: 4.9,
        jobs: 38,
        languages: ['English', 'Japanese'],
      },
      {
        slug: 'bruno-ferreira',
        name: 'Bruno Ferreira',
        title: 'Executive Chauffeur & Security Driver',
        category: 'driving',
        bio: 'Professional evasive-driving trained chauffeur specializing in VIP transport.',
        countryCode: 'BR',
        country: 'Brazil',
        city: 'Rio de Janeiro',
        hourlyRate: 50.0,
        rating: 4.8,
        jobs: 52,
        languages: ['English', 'Portuguese', 'Spanish'],
      },
      {
        slug: 'dimitra-kalogeri',
        name: 'Dimitra Kalogeri',
        title: 'Personal Security & Escort Specialist',
        category: 'security',
        bio: 'Certified close protection officer for corporate executives and visitors.',
        countryCode: 'GR',
        country: 'Greece',
        city: 'Athens',
        hourlyRate: 85.0,
        rating: 5.0,
        jobs: 24,
        languages: ['English', 'Greek'],
      },
      {
        slug: 'lerato-khumalo',
        name: 'Lerato Khumalo',
        title: 'Event Logistics Coordinator & Chef',
        category: 'catering',
        bio: 'Private dining experiences and event logistics across Johannesburg.',
        countryCode: 'ZA',
        country: 'South Africa',
        city: 'Johannesburg',
        hourlyRate: 45.0,
        rating: 4.7,
        jobs: 19,
        languages: ['English', 'Zulu'],
      },
      {
        slug: 'omar-chraibi',
        name: 'Omar Chraibi',
        title: 'Business Interpreter & Cultural Liaison',
        category: 'interpreting',
        bio: 'Tri-lingual interpreter supporting corporate negotiations and visits.',
        countryCode: 'MA',
        country: 'Morocco',
        city: 'Casablanca',
        hourlyRate: 75.0,
        rating: 4.9,
        jobs: 44,
        languages: ['English', 'French', 'Arabic'],
      },
    ];

    for (const p of professionalsData) {
      await this.prisma.professionalProfile.upsert({
        where: { slug: p.slug },
        update: {},
        create: {
          slug: p.slug,
          name: p.name,
          title: p.title,
          category: p.category,
          bio: p.bio,
          countryCode: p.countryCode,
          country: p.country,
          city: p.city,
          hourlyRate: new Prisma.Decimal(p.hourlyRate),
          currency: 'USD',
          languages: p.languages,
          rating: new Prisma.Decimal(p.rating),
          completedJobs: p.jobs,
          isVerified: true,
        },
      });
    }

    // 5. Visa Applications
    await this.prisma.visaDocumentation.upsert({
      where: { applicationNo: 'VISA-2026-8812' },
      update: {},
      create: {
        applicationNo: 'VISA-2026-8812',
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        phone: '+14155552671',
        dateOfBirth: new Date('1988-03-12'),
        gender: Gender.MALE,
        nationality: 'United States',
        residenceAddress: '742 Evergreen Terrace, Springfield, US',
        passportNumber: 'A09182736',
        passportIssueDate: new Date('2020-01-10'),
        passportExpiryDate: new Date(Date.now() + 86400000 * 365),
        targetCountry: 'United Kingdom',
        visaCategory: 'TOURIST',
        intendedArrivalDate: new Date(Date.now() + 86400000 * 30),
        intendedDepartureDate: new Date(Date.now() + 86400000 * 45),
        purposeOfVisit: 'Vacation and tourism',
        passportDataPageUrl: 'https://storage.worldportal.com/visas/passport_john.pdf',
        passportPhotoWhiteBgUrl: 'https://storage.worldportal.com/visas/photo_john.jpg',
        proofOfFunds6MonthsUrl: 'https://storage.worldportal.com/visas/funds_john.pdf',
        status: VisaDocumentStatus.EVALUATED,
        totalAmount: new Prisma.Decimal(850.0),
        amountPaid: new Prisma.Decimal(0.0),
        balanceDue: new Prisma.Decimal(850.0),
        currency: 'USD',
        createdBy: 'system-seed',
      },
    });

    // 6. Passport Application
    await this.prisma.passportApplication.upsert({
      where: { applicationNo: 'PASS-2026-4410' },
      update: {},
      create: {
        applicationNo: 'PASS-2026-4410',
        surname: 'Ojukwu',
        firstName: 'David',
        email: 'david@example.com',
        contactPhone: '+2348055511223',
        sex: Gender.MALE,
        dateOfBirth: new Date('1994-06-15'),
        placeOfBirth: 'Enugu',
        homeTown: 'Nnewi',
        stateOfOrigin: 'Anambra',
        permanentAddress: '12 Marina Road, Lagos',
        occupation: 'Software Engineer',
        maritalStatus: 'Single',
        colourOfEyes: 'Brown',
        colourOfHair: 'Black',
        height: '1.82m',
        ninNumber: '12345678901',
        nextOfKinName: 'Mary Ojukwu',
        nextOfKinPhone: '+2348033344556',
        nextOfKinRelationship: 'Sister',
        nextOfKinAddress: '12 Marina Road, Lagos',
        passportCategory: PassportCategory.FRESH,
        validity: PassportValidity.TEN_YEARS,
        bookletType: BookletType.SIXTY_FOUR_PAGES,
        status: PassportApplicationStatus.EVALUATED,
        totalAmount: new Prisma.Decimal(120000.0),
        currency: 'NGN',
        ninDocumentUrl: 'https://storage.worldportal.com/passports/nin_david.jpg',
        birthCertificateUrl: 'https://storage.worldportal.com/passports/birth_david.jpg',
        passportPhotoUrl: 'https://storage.worldportal.com/passports/photo_david.jpg',
        createdBy: 'system-seed',
      },
    });

    this.logger.log('Database presentation seed completed successfully!');

    return {
      success: true,
      message: 'Database presentation seed executed successfully',
      defaultPassword: this.DEFAULT_PASSWORD,
      summary: {
        managerProfile: manager.email,
        bankAccounts: 2,
        agencies: agenciesData.length,
        agencyUsers: agenciesData.length,
        professionals: professionalsData.length,
        visaApplications: 1,
        passportApplications: 1,
      },
    };
  }
}
